#undef sqlite3BtreeNext
#undef sqlite3BtreeCursorHasMoved
#undef sqlite3BtreeClearCursor
#undef sqlite3BtreeCursorRestore
#undef sqlite3BtreeCursorHintFlags
#undef sqlite3BtreeCloseCursor
#undef sqlite3BtreeCursorIsValid
#undef sqlite3BtreeCursorIsValidNN
#undef sqlite3BtreeIntegerKey
#undef sqlite3BtreeCursorPin
#undef sqlite3BtreeCursorUnpin
#undef sqlite3BtreePayloadSize
#undef sqlite3BtreeMaxRecordSize
#undef sqlite3BtreePayload
#undef sqlite3BtreePayloadChecked
#undef sqlite3BtreePayloadFetch
#undef sqlite3BtreeFirst
#undef sqlite3BtreeLast
#undef sqlite3BtreeTableMoveto
#undef sqlite3BtreeIndexMoveto
#undef sqlite3BtreeCursorDir
#undef sqlite3BtreeEof
#undef sqlite3BtreeRowCountEst
#undef sqlite3BtreePrevious
#undef sqlite3BtreeInsert
#undef sqlite3BtreeDelete
#undef sqlite3BtreeIdxDelete
#undef sqlite3BtreePutData
#undef sqlite3BtreeIncrblobCursor
#undef sqlite3BtreeCursorHasHint
#undef sqlite3BtreeTransferRow
#undef sqlite3BtreeClearTableOfCursor
#undef sqlite3BtreeCount
#undef sqlite3BtreeCursor
#undef sqlite3BtreeSeekCount
#undef sqlite3BtreeLastPage
#undef sqlite3BtreeClose
#undef sqlite3BtreeSetCacheSize
#undef sqlite3BtreeSetSpillSize
#undef sqlite3BtreeSetMmapLimit
#undef sqlite3BtreeSetPagerFlags
#undef sqlite3BtreeSetPageSize
#undef sqlite3BtreeGetPageSize
#undef sqlite3BtreeGetReserveNoMutex
#undef sqlite3BtreeGetRequestedReserve
#undef sqlite3BtreeMaxPageCount
#undef sqlite3BtreeSecureDelete
#undef sqlite3BtreeSetAutoVacuum
#undef sqlite3BtreeGetAutoVacuum
#undef sqlite3BtreeNewDb
#undef sqlite3BtreeBeginTrans
#undef sqlite3BtreeIncrVacuum
#undef sqlite3BtreeCommitPhaseOne
#undef sqlite3BtreeCommitPhaseTwo
#undef sqlite3BtreeCommit
#undef sqlite3BtreeTripAllCursors
#undef sqlite3BtreeRollback
#undef sqlite3BtreeBeginStmt
#undef sqlite3BtreeSavepoint
#undef sqlite3BtreeCreateTable
#undef sqlite3BtreeClearTable
#undef sqlite3BtreeDropTable
#undef sqlite3BtreeGetMeta
#undef sqlite3BtreeUpdateMeta
#undef sqlite3BtreePragma
#undef sqlite3BtreePager
#undef sqlite3BtreeGetFilename
#undef sqlite3BtreeGetJournalname
#undef sqlite3BtreeTxnState
#undef sqlite3BtreeIsInBackup
#undef sqlite3BtreeSchema
#undef sqlite3BtreeSchemaLocked
#undef sqlite3BtreeIsReadonly
#undef sqlite3BtreeSetVersion
#undef sqlite3BtreeIntegrityCheck
#undef sqlite3BtreeCheckpoint
#undef sqlite3BtreeFakeValidCursor
#undef sqlite3BtreeCursorSize
#undef sqlite3BtreeCursorZero
#undef sqlite3BtreeOpen
#ifndef SQLITE_DEBUG
# define sqlite3BtreeSeekCount(X) 0
#endif

