int sqlite3HctBtreeCursor(Btree*, Pgno, int, struct KeyInfo*, BtCursor*);
sqlite3_uint64 sqlite3HctBtreeSeekCount(Btree*);
Pgno sqlite3HctBtreeLastPage(Btree*);
int sqlite3HctBtreeClose(Btree*);
int sqlite3HctBtreeSetCacheSize(Btree*, int);
int sqlite3HctBtreeSetSpillSize(Btree*, int);
int sqlite3HctBtreeSetMmapLimit(Btree*, sqlite3_int64);
int sqlite3HctBtreeSetPagerFlags(Btree*, unsigned);
int sqlite3HctBtreeSetPageSize(Btree*, int, int, int);
int sqlite3HctBtreeGetPageSize(Btree*);
int sqlite3HctBtreeGetReserveNoMutex(Btree*);
int sqlite3HctBtreeGetRequestedReserve(Btree*);
Pgno sqlite3HctBtreeMaxPageCount(Btree*, Pgno);
int sqlite3HctBtreeSecureDelete(Btree*, int);
int sqlite3HctBtreeSetAutoVacuum(Btree*, int);
int sqlite3HctBtreeGetAutoVacuum(Btree*);
int sqlite3HctBtreeNewDb(Btree*);
int sqlite3HctBtreeBeginTrans(Btree*, int, int*);
int sqlite3HctBtreeIncrVacuum(Btree*);
int sqlite3HctBtreeCommitPhaseOne(Btree*, const char*);
int sqlite3HctBtreeCommitPhaseTwo(Btree*, int);
int sqlite3HctBtreeCommit(Btree*);
int sqlite3HctBtreeTripAllCursors(Btree*, int, int);
int sqlite3HctBtreeRollback(Btree*, int, int);
int sqlite3HctBtreeBeginStmt(Btree*, int);
int sqlite3HctBtreeSavepoint(Btree*, int, int);
int sqlite3HctBtreeCreateTable(Btree*, Pgno*, int);
int sqlite3HctBtreeClearTable(Btree*, int, i64*);
int sqlite3HctBtreeDropTable(Btree*, int, int*);
void sqlite3HctBtreeGetMeta(Btree*, int, u32*);
int sqlite3HctBtreeUpdateMeta(Btree*, int, u32);
int sqlite3HctBtreePragma(Btree*, char**);
Pager *sqlite3HctBtreePager(Btree*);
const char *sqlite3HctBtreeGetFilename(Btree*);
const char *sqlite3HctBtreeGetJournalname(Btree*);
int sqlite3HctBtreeTxnState(Btree*);
int sqlite3HctBtreeIsInBackup(Btree*);
void *sqlite3HctBtreeSchema(Btree*, int, void(*)(void *));
int sqlite3HctBtreeSchemaLocked(Btree*);
int sqlite3HctBtreeIsReadonly(Btree*);
int sqlite3HctBtreeSetVersion(Btree*, int);
int sqlite3HctBtreeIntegrityCheck(sqlite3*, Btree*, Pgno*, Mem*, int, int, int*, char**);
int sqlite3HctBtreeCheckpoint(Btree*, int, int *, int *);
int sqlite3HctBtreeExclusiveLock(Btree*);
int sqlite3HctBtreeNext(BtCursor*, int);
int sqlite3HctBtreeCursorHasMoved(BtCursor*);
void sqlite3HctBtreeClearCursor(BtCursor*);
int sqlite3HctBtreeCursorRestore(BtCursor*, int*);
void sqlite3HctBtreeCursorHintFlags(BtCursor*, unsigned);
int sqlite3HctBtreeCloseCursor(BtCursor*);
int sqlite3HctBtreeCursorIsValid(BtCursor*);
int sqlite3HctBtreeCursorIsValidNN(BtCursor*);
i64 sqlite3HctBtreeIntegerKey(BtCursor*);
void sqlite3HctBtreeCursorPin(BtCursor*);
void sqlite3HctBtreeCursorUnpin(BtCursor*);
u32 sqlite3HctBtreePayloadSize(BtCursor*);
sqlite3_int64 sqlite3HctBtreeMaxRecordSize(BtCursor*);
int sqlite3HctBtreePayload(BtCursor*, u32, u32, void*);
int sqlite3HctBtreePayloadChecked(BtCursor*, u32, u32, void *);
const void *sqlite3HctBtreePayloadFetch(BtCursor*, u32*);
int sqlite3HctBtreeFirst(BtCursor*, int*);
int sqlite3HctBtreeLast(BtCursor*, int*);
int sqlite3HctBtreeTableMoveto(BtCursor*, i64, int, int*);
int sqlite3HctBtreeIndexMoveto(BtCursor*, UnpackedRecord*, int*);
void sqlite3HctBtreeCursorDir(BtCursor*, int);
int sqlite3HctBtreeEof(BtCursor*);
i64 sqlite3HctBtreeRowCountEst(BtCursor*);
int sqlite3HctBtreePrevious(BtCursor*, int);
int sqlite3HctBtreeInsert(BtCursor*, const BtreePayload*, int, int);
int sqlite3HctBtreeDelete(BtCursor*, u8);
int sqlite3HctBtreeIdxDelete(BtCursor*, UnpackedRecord*);
int sqlite3HctBtreePutData(BtCursor*, u32, u32, void*);
void sqlite3HctBtreeIncrblobCursor(BtCursor*);
int sqlite3HctBtreeCursorHasHint(BtCursor*, unsigned int);
int sqlite3HctBtreeTransferRow(BtCursor*, BtCursor*, i64);
int sqlite3HctBtreeClearTableOfCursor(BtCursor*);
int sqlite3HctBtreeCount(sqlite3*, BtCursor*, i64*);
i64 sqlite3HctBtreeOffset(BtCursor*);
int sqlite3StockBtreeCursor(Btree*, Pgno, int, struct KeyInfo*, BtCursor*);
sqlite3_uint64 sqlite3StockBtreeSeekCount(Btree*);
Pgno sqlite3StockBtreeLastPage(Btree*);
int sqlite3StockBtreeClose(Btree*);
int sqlite3StockBtreeSetCacheSize(Btree*, int);
int sqlite3StockBtreeSetSpillSize(Btree*, int);
int sqlite3StockBtreeSetMmapLimit(Btree*, sqlite3_int64);
int sqlite3StockBtreeSetPagerFlags(Btree*, unsigned);
int sqlite3StockBtreeSetPageSize(Btree*, int, int, int);
int sqlite3StockBtreeGetPageSize(Btree*);
int sqlite3StockBtreeGetReserveNoMutex(Btree*);
int sqlite3StockBtreeGetRequestedReserve(Btree*);
Pgno sqlite3StockBtreeMaxPageCount(Btree*, Pgno);
int sqlite3StockBtreeSecureDelete(Btree*, int);
int sqlite3StockBtreeSetAutoVacuum(Btree*, int);
int sqlite3StockBtreeGetAutoVacuum(Btree*);
int sqlite3StockBtreeNewDb(Btree*);
int sqlite3StockBtreeBeginTrans(Btree*, int, int*);
int sqlite3StockBtreeIncrVacuum(Btree*);
int sqlite3StockBtreeCommitPhaseOne(Btree*, const char*);
int sqlite3StockBtreeCommitPhaseTwo(Btree*, int);
int sqlite3StockBtreeCommit(Btree*);
int sqlite3StockBtreeTripAllCursors(Btree*, int, int);
int sqlite3StockBtreeRollback(Btree*, int, int);
int sqlite3StockBtreeBeginStmt(Btree*, int);
int sqlite3StockBtreeSavepoint(Btree*, int, int);
int sqlite3StockBtreeCreateTable(Btree*, Pgno*, int);
int sqlite3StockBtreeClearTable(Btree*, int, i64*);
int sqlite3StockBtreeDropTable(Btree*, int, int*);
void sqlite3StockBtreeGetMeta(Btree*, int, u32*);
int sqlite3StockBtreeUpdateMeta(Btree*, int, u32);
int sqlite3StockBtreePragma(Btree*, char**);
Pager *sqlite3StockBtreePager(Btree*);
const char *sqlite3StockBtreeGetFilename(Btree*);
const char *sqlite3StockBtreeGetJournalname(Btree*);
int sqlite3StockBtreeTxnState(Btree*);
int sqlite3StockBtreeIsInBackup(Btree*);
void *sqlite3StockBtreeSchema(Btree*, int, void(*)(void *));
int sqlite3StockBtreeSchemaLocked(Btree*);
int sqlite3StockBtreeIsReadonly(Btree*);
int sqlite3StockBtreeSetVersion(Btree*, int);
int sqlite3StockBtreeIntegrityCheck(sqlite3*, Btree*, Pgno*, Mem*, int, int, int*, char**);
int sqlite3StockBtreeCheckpoint(Btree*, int, int *, int *);
int sqlite3StockBtreeExclusiveLock(Btree*);
int sqlite3StockBtreeNext(BtCursor*, int);
int sqlite3StockBtreeCursorHasMoved(BtCursor*);
void sqlite3StockBtreeClearCursor(BtCursor*);
int sqlite3StockBtreeCursorRestore(BtCursor*, int*);
void sqlite3StockBtreeCursorHintFlags(BtCursor*, unsigned);
int sqlite3StockBtreeCloseCursor(BtCursor*);
int sqlite3StockBtreeCursorIsValid(BtCursor*);
int sqlite3StockBtreeCursorIsValidNN(BtCursor*);
i64 sqlite3StockBtreeIntegerKey(BtCursor*);
void sqlite3StockBtreeCursorPin(BtCursor*);
void sqlite3StockBtreeCursorUnpin(BtCursor*);
u32 sqlite3StockBtreePayloadSize(BtCursor*);
sqlite3_int64 sqlite3StockBtreeMaxRecordSize(BtCursor*);
int sqlite3StockBtreePayload(BtCursor*, u32, u32, void*);
int sqlite3StockBtreePayloadChecked(BtCursor*, u32, u32, void *);
const void *sqlite3StockBtreePayloadFetch(BtCursor*, u32*);
int sqlite3StockBtreeFirst(BtCursor*, int*);
int sqlite3StockBtreeLast(BtCursor*, int*);
int sqlite3StockBtreeTableMoveto(BtCursor*, i64, int, int*);
int sqlite3StockBtreeIndexMoveto(BtCursor*, UnpackedRecord*, int*);
void sqlite3StockBtreeCursorDir(BtCursor*, int);
int sqlite3StockBtreeEof(BtCursor*);
i64 sqlite3StockBtreeRowCountEst(BtCursor*);
int sqlite3StockBtreePrevious(BtCursor*, int);
int sqlite3StockBtreeInsert(BtCursor*, const BtreePayload*, int, int);
int sqlite3StockBtreeDelete(BtCursor*, u8);
int sqlite3StockBtreeIdxDelete(BtCursor*, UnpackedRecord*);
int sqlite3StockBtreePutData(BtCursor*, u32, u32, void*);
void sqlite3StockBtreeIncrblobCursor(BtCursor*);
int sqlite3StockBtreeCursorHasHint(BtCursor*, unsigned int);
int sqlite3StockBtreeTransferRow(BtCursor*, BtCursor*, i64);
int sqlite3StockBtreeClearTableOfCursor(BtCursor*);
int sqlite3StockBtreeCount(sqlite3*, BtCursor*, i64*);
i64 sqlite3StockBtreeOffset(BtCursor*);
BtCursor *sqlite3StockBtreeFakeValidCursor(void);

